[build]
  command = "npm install && npm run build"
  publish = "out" # Change from ".next" to "out" for static exports

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
